// Generated by Quake 3 Bot Designer

//===========================================================================
// Name:			nightlord_w.c
// Function:		weapon weights for Nightlord
// Programmer:		Q3BD
// Last update:		Tuesday, February 25, 2003 at 09:37:53
//===========================================================================


#include "inv.h"


#define W_GAUNTLET				20
#define W_SHOTGUN				150
#define W_MACHINEGUN			40
#define W_GRENADELAUNCHER		165
#define W_ROCKETLAUNCHER		250
#define W_RAILGUN				90
#define W_BFG10K				95
#define W_LIGHTNING				100
#define W_PLASMAGUN				190
#define W_GRAPPLE				15

//
#include "fw_weap.c"


