// Generated by Quake 3 Bot Designer

//===========================================================================
// Name:			nightlord_i.c
// Function:		weapon weights for Nightlord
// Programmer:		Q3BD
// Last update:		Tuesday, February 25, 2003 at 09:37:53
//===========================================================================


#include "inv.h"


//initial health/armor states
#define FS_HEALTH				145
#define FS_ARMOR				170

//initial weapon weights
#define W_SHOTGUN				230
#define W_MACHINEGUN			125
#define W_GRENADELAUNCHER		215
#define W_ROCKETLAUNCHER		365
#define W_RAILGUN				105
#define W_BFG10K				165
#define W_LIGHTNING				125
#define W_PLASMAGUN				310

//the bot has the weapons, so the weights change a little bit
#define GWW_SHOTGUN				265
#define GWW_MACHINEGUN			105
#define GWW_GRENADELAUNCHER		220
#define GWW_ROCKETLAUNCHER		355
#define GWW_RAILGUN				125
#define GWW_BFG10K				125
#define GWW_LIGHTNING			145
#define GWW_PLASMAGUN			305

//initial powerup weights
#define W_TELEPORTER			100
#define W_MEDKIT				40
#define W_QUAD					310
#define W_ENVIRO				375
#define W_HASTE					95
#define W_INVISIBILITY			290
#define W_REGEN					175
#define W_FLIGHT				95

//flag weight
#define FLAG_WEIGHT				50

//
#include "fw_items.c"


