// Generated by Quake 3 Bot Designer

//===========================================================================
// Name:			nightlord_t.c
// Function:		weapon weights for Nightlord
// Programmer:		Q3BD
// Last update:		Tuesday, February 25, 2003 at 09:37:53
//===========================================================================


chat "Nightlord"
{
	#include "teamplay.h"


	//======================================================
	//======================================================

	type "game_enter" //initiated when the bot enters the game
	{
		"Weakling servants of the Emperor, ye shall perish!";
		"", 4, " shall be you tombs...";
		"ahh... fresh souls for Chaos!";
		"Destroy these mortals? Thy will be done my infernal masters.";
	} //end type

	type "game_exit" //initiated when the bot exits the game
	{
		"I must travel where Chaos takes me....";
		"I shall return to fight again on these cursed grounds...";
		"Consider yourselves lucky, mortals....";
		"The unholy crusade continues elsewhere....";
	} //end type

	type "level_start" //initiated when a new level starts
	{
		"My weapons seek the flesh of ", 1, " NOW!";
		"I forsee a great victory of the dark over the light!";
		"Are these mortals all that oppose me?";
		"Flee before me, for it is your very souls that I come for!";
		"Masters, I commence this massacre is you names!";
		"", 4, " shall be drenched with my enemies blood!";
	} //end type

	type "level_end" //initiated when a level ends and the bot is not first and not last in the rankings
	{
		"The time for slaughter is finished, for now....";
		"I offer up the souls of the defeated, consume them with relish!";
		"", 2, ", you have escaped my wrath this time....";
		"", 4, " was indeed a battle most worthy.";
	} //end type

	type "level_end_victory" //initiated when a level ends and the bot is first in the rankings
	{
		"The power of Chaos reigns supreme!";
		"", 0, " is your lord, bow before me!";
		"", 3, ", you many deaths were a pleasure to me!";
		"No mortal is a match for me!";
		"This battle will long be remembered in MY honour!";
		"the dead lie evey where, dead at MY hands!";
		"mortals, pledge you souls to chaos and you may join me in this victory!";
	} //end type

	type "level_end_lose" //initiated when a level ends and the bot is last in the rankings
	{
		"What? Have the powers forsaken me?!?";
		"Argh! My masters will not be pleased with this!";
		"But slaughter was was so great, how could I be defeated?!";
		"Obviously, the powers of chaos were with ", 2, "";
		"", 2, ", dont think you will avoid me next time...";
		"The imperium shall pay for this defeat!";
	} //end type

	//======================================================
	//======================================================

	type "hit_talking" //bot is hit while chat balloon is visible; lecture attacker on poor sportsmanship
	{
		"Attacking while communicating? Truly you are a child of Chaos!";
		"May daemons rend you for interupting my com-net!";
	} //end type

	type "hit_nodeath" //bot is hit by an opponent's weapon attack; either praise or insult
	{
		"You puny weapons cannot harm me mortal!";
		"The Chaos gods will protect me from more that that!";
		"", 0, ", you couldnt even kill a grot with that salvo!";
		"I have witnessed civilians fight better than you, ", 0, ".";
		"I shall flay you alive for that shot!";
		"My Chaos armour is proof of a thousand shots as weak as that!";
		"", 0, ", you skills as a warrior would make a gretchin laugh!";
		"Praise my Masters for warding that blast!";
	} //end type

	type "hit_nokill" //bot hits an opponent but does not kill it
	{
		"A curse be on this feeble weapon!";
		"", 0, ", I hope that shot went deep!";
		"I can taste you blood and fear from here, ", 0, "";
		"My weapons shall blast the very soul from you body!";
		"HAHAHA! RUN! HIDE! There is NO escape from Chaos!";
		"Could you feel that? I hope so....";
	} //end type

	//======================================================
	//======================================================

	type "death_telefrag" //initiated when the bot is killed by a telefrag
	{
		"Yeaarg!! Burst from the inside, the pain was exquisite!";
		"My entrails around me!  How beautiful!";
		"", 0, ", I hope you are a Greater Daemon!";
	} //end type

	type "death_cratered" //initiated when the bot is killed by taking "normal" falling damage
	{
		"Curse this armour for not halting that fall better...";
		"Back broken... must destroy mankind....";
		"Killed by a fall... I am shamed...";
	} //end type

	type "death_lava" //initiated when the bot dies in lava
	{
		"AAAGH!! the fires of Chaos welcome me!!";
		"Why did not my masters save me from the fire?!";
		"I shall be REBORN from the ashes!";
	} //end type

	type "death_slime" //initiated when the bot dies in slime
	{
		"This acid merely irritates me more!";
		"Arg! My armour was not proof against acid of that strength!";
		"You can melt my body, but my soul is retained by The Chaos Gods!";
	} //end type

	type "death_drown" //initiated when the bot drowns
	{
	} //end type

	type "death_suicide" //initiated when bot blows self up with a weapon or craters
	{
		"Detroyed my my own hands, my skills are failing!";
		"I must have the brain of an Ogryn!";
	} //end type

	type "death_gauntlet" //initiated when the bot is killed by a gauntlet attack
	{
		"Close combat! You are wothy of further attention ", 0, ".";
		"You have bested me this once!";
		"May my weapons tear you apart before you get that close again!";
	} //end type

	type "death_rail" //initiated when the bot is killed by a rail gun shot
	{
		"Damm Tau weaponry!";
		"Cored like a rotton fruit, I shall return the favor!";
		"Such a small hole cannot stop me... cough....";
		"A curse upon you and you tech-adepts!";
	} //end type

	type "death_bfg" //initiated when the bot died by a BFG
	{
		"Such a powerful weapon, where might I obtain one?!";
		"A daemon weapon that must be!";
		"I long for power like hav ein your hands, ", 0, "";
	} //end type

	type "death_insult" //insult initiated when the bot died
	{
		"I commend my soul to Chaos!";
		"I shall return that favour, ", 0, ".";
		"Even as my body is destroyed, I shall live again!";
		"The traitor legions cannot be defeated with just one kill!";
		"May daemons flock to you and take you vital essence!";
		"I shall be avenged by my infernal kin!";
		"My soul passes to the warp, welcome me masters!";
		"Yearg! I shall gut you for that ", 0, ".";
		"Soul strong... Body broken.... Give me to power to return Dark Lords!";
	} //end type

	type "death_praise" //praise initiated when the bot died
	{
		"You fight like a Daemon!";
		"An excellent kill, perhaps you would like to join me in dammnation?";
		"The traitor legions could use a warrior like you, ", 0, ".";
		"I dont think you will rival me a second time...";
		"Ah, a worthy opponent at last!";
		"To which God have you pledged you soul to fight like that?!";
	} //end type

	//======================================================
	//======================================================

	type "kill_rail" //initiated when the bot kills someone with rail gun
	{
		"", 0, ", enjoy that slug through your body?";
		"These rail-guns are indeed an excellent weapon!";
		"Ahaha! punched through you like a bolt through a gretchin!";
	} //end type

	type "kill_gauntlet" //initiated when the bot kills someone with gauntlet
	{
		"Nothing can rival the feeling of close combat!";
		"My skills up close are far beyond yours, ", 0, ".";
		"Cut down like the mortal that you are!";
	} //end type

	type "kill_telefrag" //initiated when the bot telefragged someone
	{
		"You blood covers me, how exhilarating!";
		"Entrails and meat everywhere! I live for this!";
	} //end type

	type "kill_suicide" //initiated when the players kills self
	{
		"Hahah! Learn to use that weapon before you challenge me again!";
		"Even your own weapon has turned against you mortal!";
		"The power of Chaos has fooled your mind, weakling!";
	} //end type

	type "kill_insult" //insult initiated when the bot killed someone
	{
		"Slaughterd!";
		"You are no match for me mortal!";
		"", 0, ", try again to defeat me and you shall suffer again!";
		"Praise to chaos for your death!";
		"Take their soul my lords!";
		"I offer ", 0, "'s soul to you my Masters!";
		"Another mark on my immeasurable tally of death!";
		"I dedicate that kill to you my unholy Masters!";
	} //end type

	type "kill_praise" //praise initiated when the bot killed someone
	{
		"", 0, ", you fought well, but not well enough!";
		"I cannot be defeated that easily!";
		"Enjoy the Warp ", 0, ", it is you home NOW!";
		"", 0, ", Can you feel my masters consuming your essence?";
		"Perhaps you were weaker than you though, FOOL!";
		"Rise up and fight again, ", 0, ", I relish the combat.";
	} //end type

	//======================================================
	//======================================================

	type "random_insult" //insult initiated randomly (just when the bot feels like it)
	{
		"Come and kill me if you dare ", 0, ".";
		"I am comming for your soul ", 0, ".";
		"Shall I crush ", 1, " again, or shall I seek fresh meat?....";
		"I can feel the power of Chaos invigorating me!";
		"Death is all around me, this is what I crave!";
		"Death to the False Emperor!";
		"Death to the Weakling Chapters!";
		"My presence is your painful death mortals!";
	} //end type

	type "random_misc" //miscellanous chats initiated randomly
	{
		"Death to the False Emperor!";
		"Praise to Chaos!";
		"Abbadon is Lord!";
		"", 1, ", that name shall be written in blood!";
		"", 0, ", I shall feast upon your skin as a sweet meat!";
		"Run while you can mortals!";
		"Cast down the corpse on the Golden Throne!";
		"From the Eye of Terror we come!";
		"I shall harvest you souls in an orgy of destruction!";
		"Come Masters! This battleground will be awash with your praise!";
	} //end type
} //end Nightlord chat
